sudo: false
language: node_js
node_js:
  - '4'
  - '6'
install:
  - npm i npminstall && npminstall
before_script:
  - mysql -uroot -e 'create database IF NOT EXISTS test;'
  - mysql -uroot test < test/npm_auth.sql
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mysql